# Generated by Django 3.2 on 2021-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('tear', models.CharField(max_length=20)),
                ('updateDate', models.DateTimeField()),
            ],
        ),
    ]
