# Generated by Django 3.2 on 2021-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210410_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summonerLevel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
