# Generated by Django 3.2 on 2021-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_user_summonerlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileIconId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
