# Generated by Django 3.2 on 2021-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_user_profileiconid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tear',
        ),
        migrations.AddField(
            model_name='user',
            name='flexLeaguePoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='flexLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='flexTier',
            field=models.CharField(default='UNRANK', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='flexWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soloLeaguePoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soloLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soloTier',
            field=models.CharField(default='UNRANK', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='soloWins',
            field=models.IntegerField(default=0),
        ),
    ]
