# Generated by Django 3.2 on 2021-04-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210410_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('gameId', models.IntegerField(primary_key=True, serialize=False)),
                ('platformId', models.CharField(default='KR', max_length=5)),
                ('gameDuration', models.IntegerField(default=0)),
                ('queueId', models.IntegerField(default=0)),
                ('mapId', models.IntegerField(default=0)),
                ('seasonId', models.IntegerField(default=0)),
                ('gameMode', models.CharField(default='CLASSIC', max_length=10)),
                ('gameType', models.CharField(default='MATCHED_GAME', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField(default=1)),
                ('teamId', models.IntegerField(default=100)),
                ('championId', models.IntegerField(default=0)),
                ('spell1Id', models.IntegerField(default=0)),
                ('spell2Id', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('largestKillingSpree', models.IntegerField(default=0)),
                ('largestMultiKill', models.IntegerField(default=0)),
                ('longestTimeSpentLiving', models.IntegerField(default=0)),
                ('doubleKills', models.IntegerField(default=0)),
                ('tripleKills', models.IntegerField(default=0)),
                ('quadraKills', models.IntegerField(default=0)),
                ('pentaKills', models.IntegerField(default=0)),
                ('totalDamageDealt', models.IntegerField(default=0)),
                ('visionScore', models.IntegerField(default=0)),
                ('champLevel', models.IntegerField(default=0)),
                ('lane', models.CharField(default='TOP', max_length=10)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.match')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformId', models.CharField(default='KR', max_length=5)),
                ('gameId', models.IntegerField(default=0)),
                ('champion', models.IntegerField(default=0)),
                ('season', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=0)),
                ('role', models.CharField(default='NONE', max_length=10)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.participants')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.user')),
            ],
        ),
    ]
